<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Kebijakan Privasi_a-u9t1c0o8x1r</name>
   <tag></tag>
   <elementGuidId>07205ad9-dd70-4830-bab2-fe77f552623b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-u9t1c0o8x1r&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-u9t1c0o8x1r']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>12b49857-727a-4e2a-a2ca-1e66c40a6bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>b501bfc3-faa3-4c14-b0c1-17ffaaaa9c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>0d8623fd-31ad-47d4-b23f-26dc8776e833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>d897bf78-4be9-40e4-8596-f84cdd62f14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>8bd42af8-401a-426d-bd66-3510798fc5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-u9t1c0o8x1r</value>
      <webElementGuid>418a0863-60e0-46c9-9f8e-8222a57890c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12fff54c-374c-4891-b08e-9b7b04da0ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>50f00062-22f1-4c50-bddd-dda21e3b77f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>29d54b8b-f91c-409a-94af-e3a2f4c68b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lco17kUAAAAAKFNCdXJK61Kc_Vy3VC8iP_uM_xu&amp;co=aHR0cHM6Ly93d3cuY2VybWF0aS5jb206NDQz&amp;hl=id&amp;type=image&amp;v=xds0rzGrktR88uEZ2JUvdgOY&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=xrqeghg1lnu7</value>
      <webElementGuid>f8dacd82-3ada-4ddf-8ef6-5bd6d4078199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HeaderFooter_header-gap__uaiur&quot;]/div[@class=&quot;superapp-container content&quot;]/div[@class=&quot;container_Eq-qi&quot;]/div[@class=&quot;w-100 d-flex m-t-16 justify-content-center&quot;]/div[1]/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>5ed40c7a-2fa5-4191-b19e-7d9dfbec965d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-u9t1c0o8x1r']</value>
      <webElementGuid>b33a2482-77b0-410b-a6ec-2c1f8c05d987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div/div[5]/div/div/div/div/div/iframe</value>
      <webElementGuid>5a146659-6732-4ddb-a358-0f7bdfecff0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>eb51c989-ee4e-4a74-999f-fdfb5120fe74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-u9t1c0o8x1r' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lco17kUAAAAAKFNCdXJK61Kc_Vy3VC8iP_uM_xu&amp;co=aHR0cHM6Ly93d3cuY2VybWF0aS5jb206NDQz&amp;hl=id&amp;type=image&amp;v=xds0rzGrktR88uEZ2JUvdgOY&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=xrqeghg1lnu7']</value>
      <webElementGuid>af444a74-1ed1-4a19-add1-941bf3dcbb2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
