<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Handphone_mobilePhone</name>
   <tag></tag>
   <elementGuidId>d826fea5-1bee-45d3-bfdd-c7a7ecf4f24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobilePhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobilePhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfc90bd1-746f-4c9c-ae0f-79239af2adb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e107d73f-561f-4928-862e-ce66391558bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field_MOE4W</value>
      <webElementGuid>95141e30-84c1-4370-9c5f-9096d7154a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobilePhone</value>
      <webElementGuid>5cdf97ef-5f09-4fc9-8a2f-5ef29741bcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>34ddf583-dad6-44a7-9905-5c567c50f43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0986c1c9-efed-4105-aa77-9d7469630a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobilePhone</value>
      <webElementGuid>18ac9bab-479c-4787-9c9b-f8520b7124f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>7e98cca6-9b83-43fc-95cf-814265ceb0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No. Handphone</value>
      <webElementGuid>4dbda13f-dcf0-4cc0-9fb9-ba1737a8ff9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4af1535b-a783-4ed3-996b-d6779b96d904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2c435d0b-e651-4c99-ac2d-edf50e929347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobilePhone&quot;)</value>
      <webElementGuid>694879df-08ef-49c2-944d-55c120a456eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobilePhone']</value>
      <webElementGuid>7d6fecf8-93a3-43e6-9e4f-1676a7966d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div/input</value>
      <webElementGuid>e4bef5f5-ecc1-42b9-84d0-647e79fdb89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6a7000c9-7314-43b9-9040-d084c7b34530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mobilePhone' and @name = 'mobilePhone' and @placeholder = 'Masukkan No. Handphone' and @type = 'tel']</value>
      <webElementGuid>9a42ccda-79af-45cc-8c92-63f376c9ec00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
